### ISSUE TITLE
[FEATURE REQUEST]: Migration Qt6

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/komodo-wallet#1014]
**Is your feature request related to a problem? Please describe.**

I managed to migrate to Qt6 locally on my machine, unfortunately the application crashed after login, here is also a list of what to do to switch to Qt 6:

- [ ] QRegExp -> QRegularExpression
- [ ] properties `samples` in QGraphicalEffects is renamed `layer.samples`
- [ ] Use FileDialog from lab platform instead of Qt Quick 1
- [ ] Stop usage of Qt.Quick 1, use Qt.Quick 2 instead (Don't use old tableview)
- [ ] Import Qt.Quick.Styles do not exist anymore, do not use it anymore
- [ ] High DPI by default on Qt 6, comment init_dpi in main.prerequisites
- [ ] Use ShaderEffects instead of QGraphicalEffects https://doc-snapshots.qt.io/qt6-dev/qtquick-effects-topic.html
- [ ] Do not use SortFilterProxyModel -> https://github.com/oKcerG/SortFilterProxyModel (it's will not be compatible with Qt6)
- [ ] Rework FloatingBackground, DropShadow and InnerShadow to be Qt6 compatible (use a project standalone, reproduce those widget with both Qt5 and Qt6)
- [ ] Update CI
- [ ] Fork Qaterial with support Qt6

**Comment by smk762** [comment]
Our current version of QT is 5.15 which is EOL at 26 May 2023. We should update to https://www.qt.io/blog/qt-6.2.4-released soon
