### ISSUE TITLE
Inconsistent testcoin tagging

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#1194]
testcoin tagging inconsistent :octopus: 
![image](https://user-images.githubusercontent.com/35845239/129548272-c6ffb920-1e2a-4a3e-b27b-89ec5913d25a.png)
![image](https://user-images.githubusercontent.com/35845239/129548298-538cce9c-c421-4905-b21f-78c9d302e3f6.png)

_Originally posted by @smk762 in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1193#issuecomment-899396957_

**Comment by Milerius** [comment]
We could remove all the (testnet) stuff and add a `test` tag, i also suggest to turn back those tag type in the dashboard the same way as the first image (rounded tag) what do you think @tonymorony ?

**Comment by smk762** [comment]
This will need updates to coins.json file in this repo (https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/assets/config/0.5.4-coins.json) and also coins repo (https://github.com/KomodoPlatform/coins/blob/master/coins#L7003)

There are a few variations in `fname`:
`Bitcoin Cash Testnet`
`adex_bsc_testnet`
`Blackcoin testnet`
`binancesmartchaintest`
`MORTY (TESTCOIN)`

Some coins also have `TEST` in name, like:
`tBTC-TEST` vs `tQTUM`

I propose removing `TEST` from `coin` field, and for `fname` to add a simple `(test coin)` consistently instead of the variations currently used.

Not sure if these changes to coins repo would maybe cause problems in mobile repo? @MateusRodCosta @yurii-khi

**Comment by yurii-khi** [comment]
On mobile we have `"testCoin": true` parameter in our local config file (which is quite different from the desktop config file). And on the air_dex we're using `is_testnet` field from 0.5.4-coins.json to identify test coins, and as a result missing coins like RICK or MORTY.
So, yeah, it would be cool to have some consistent parameter similar to what we have for mobile.
