### ISSUE TITLE
[BUG]: Swaps are allowed to start at low amount but fails later, amount too low

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/komodo-wallet#1265]
I was selling 0.3333333 sTST  for 0.0001 Morty by sliding the amount handle to the lowest possible, but I got amount too low error. even though the AtomicdeX desktop was showing 0.0001 the trade didn't pass complaining about 0.000099999999 being too low. I had to change sTST amount from 0.3333333 to 0.3333334 for it to work

`[{"error":"rpc:173] dispatcher_legacy:155] lp_ordermatch:2847] lp_ordermatch:2989] Rel amount 0.000099999999 is too low, required: 0.0001"}]`

**To Reproduce**
1. Go to sTST/Morty trade in DEX.
2. Click on the red order with sTST priced at 0.00003 Morty
3. Slide the volume slider to the lowest possible  
4. Start swap
5. wait a few seconds and see an error

**Expected behavior**
Slider should set minimum to an acceptable value and DEX should not consider 0.0001 as 0.000099999999

**Screenshots**

https://user-images.githubusercontent.com/411046/132776208-2fea5ee0-ac17-4241-9c76-25e09b667d0e.mp4

**Desktop (please complete the following information):**
Desktop (please complete the following information):
APP: 0.5 beta
MM: 2.1.4027_mm2.1-slp-swap_2aae2b680_Linux_Release
Qt: 5.15.2

**Comment by smk762** [comment]
This might be resolved with latest version of app / API
