### ISSUE TITLE
[FEATURE REQUEST]: Make volume filter for CEX price ratio configurable

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#1317]
Right now it's 10k$ to protect users from fully non-liquid assets purchasing, we might set it much higher (e.g. 100k$/24h) and make this filter amount configurable in GUI with possibility to on/off so user will able to see low liquidity markets CEX ratio if they wish

**Comment by smk762** [comment]
This should be taken into consideration wrt recent meeting discussing better price API

**Comment by cipig** [comment]
also keep in mind that some CEXs fake the volume massively, eg Finexbox, dex-trade (for some coins), Probit
the method is well known and described here: https://www.sec.gov/comments/sr-nysearca-2019-01/srnysearca201901-5164833-183434.pdf (page 29ff, "TRADE PRINTING BETWEEN BID AND ASK")
so i think it's problematic to base decisions on potentially fake data
the effects can be seen here: https://www.coingecko.com/en/coins/feathercoin#markets
![image](https://user-images.githubusercontent.com/32116761/202733955-4fa80dea-13b8-4e80-adc4-a81ceba079e3.png)
the volume of 20k from Finexbox is complete fake, the real volume is $320 (from Bittrex)

**Comment by smk762** [comment]
I'm not sure this limit is defined with the source code of this repo? Will leave issue open for now, but might be better to migrate it to the repo which serves the price API.

**Comment by cipig** [comment]
> I'm not sure this limit is defined with the source code of this repo? Will leave issue open for now, but might be better to migrate it to the repo which serves the price API.

It's defined here https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L163 and used here https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/src/core/atomicdex/models/qt.orderbook.proxy.model.cpp#L170
