### ISSUE TITLE
[FEATURE REQUEST]: add front end for new protocols 

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/komodo-wallet#1337]
New protocols to add for addressbook `use standard network address`:

- Matic
- Harmony
- Optimism
- Arbitrum
- Avax
- Fantom
- Ubiq
- Kucoin Chain
- Heco Chain
- Moonriver

cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1303

**Comment by imylomylo** [comment]
bittorrent client

**Comment by tonymorony** [comment]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1428

**Comment by smk762** [comment]
@SylEze Would it be much work to include the other protocols in address book for 0.5.6? Or should we aim for 0.5.7?
![image](https://user-images.githubusercontent.com/35845239/177277678-e1e8f122-08b1-4051-a2b1-abeda600c082.png)
