### ISSUE TITLE
[FEATURE REQUEST]: Allow adding and modifiying coin info and server from GUI

### ISSUE THREAD

**Issue by damascene** [KomodoPlatform/komodo-wallet#1354]
Currently to add a new coin to AtomicDEX for initial swap or to modify an existing one a user need to modify text files and run too many commands.

Current setup:
1. Manually setup mm2
2. Get scripts and coin files
2. Start mm2
2. Modify coins
3. Create connect/enable file
4. Use curl to connect the new coin
5. Connect the other pair
6. Start another mm2 instance on another port
7. duplicate all files for both mm2 instances
8. modify the port for the second instance
6. correctly calculate minimum trade amount
6. Set sell order
7. Set buy buy order

This involve too much effort and it's error prone IMHO.

**Describe the solution you'd like**
I would like to see an option to copy a coin in GUI and modify it. For example, option to modify some parameters like Electrum server or required confirmations. 

For example if a coin is a fork of bitcoin, user should be able to copy bitcoin and setup the coin specific parameters and hit save to have it in the DEX.

**Describe alternatives you've considered**
If not possible to add it to GUI, Maye optional configuration setup in `~/.atomic_qt/config/custom_coins` where user can add his custom coins.

**Comment by smk762** [comment]
I like the idea for a "coin config generator". 
The API playground nodes and postman collection (https://github.com/KomodoPlatform/developer-docs/pull/372) might also help with user test swap and config testing.
