### ISSUE TITLE
[FEATURE REQUEST]: Allow adding custom assets without restart

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#1424]
**Is your feature request related to a problem? Please describe.**
Currently when adding a custom asset, the final step of the form is to logout and restart. If a user has previously selected a number of coins but not yet activated them, upon adding the custom asset this selection is lost. 

**Describe the solution you'd like**
To avoid this, we could an extra button option after inputting the custom asset information to allow for saving the input data to the user's coins file without a restart (along with a message to say the custom asset will not be available until after restart). This way the user has the option to restart immediately, or restart later while retaining the custom asset data within the coins file.

**Describe alternatives you've considered**
Alternative option could be to activate selected coins prior to forced restart so they are within the default enabled set after restart, though this would cause some delay prior to restart and user doesnt gain the control they would have compared to first above.

**Comment by Milerius** [comment]
There is no way to implement it, coins file is parsed by mm2 only on start - the other only way is to logout .

**Comment by smk762** [comment]
I dont mean to enable the custom coin without restart, I mean to add it to the coins json file without restart, so it is available next time the user decides to restart.

Normally enabled coins are fine, what I'm talking about is if you are in the add assets screen, have selected 10 coins to enable  and then click on the "add custom asset" button, this selection of coins is lost, does not enable and will need to be re-selected after being forced to restart on completion of adding the custom asset.
