### ISSUE TITLE
[FEATURE REQUEST]: Allow custom token import from secondary wallet

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#1425]
**Is your feature request related to a problem? Please describe.**
Currently custom added assets are stored in a wallet specific json file, and are only made available to the wallet within which thy were created. It would be nice to offer the convenience of importing custom asset definitions from secondary wallets on the same device rather than making the user add them manually again for every wallet.

**Describe the solution you'd like**
Within the add custom assets form, add an option to allow import from a secondary wallet on the same device. This could be achieved by:
Option 1: a dropdown to select the wallet from which to import.
Option 2: simply scan all custom asset json files for all wallets on the device and add them all.

Option 1 offers user more control over what is imported, and doesn't leak information about the secondary wallet (assuming required input of the secondary wallet password as part of the process) in the case of shared devices.

Option 2 could be simpler to implement via a common, shared custom assets json file.

**Comment by tonymorony** [comment]
Yeah, that's a good idea to have a list with previously added custom assets for easy re-adding in case of multiple wallets usage or wallet reset

**Comment by michelvankessel** [comment]
this is exactly the idea I had! have a list of assets and be able to export/import it.
