### ISSUE TITLE
[FEATURE REQUEST]: "Discount - Fair Value - Premium" price guides

### ISSUE THREAD

**Issue by SaltyCrocodile** [KomodoPlatform/komodo-wallet#1556]
Psychologically the "Expensive/Expedient" price guides are a barrier to closing the sale, and may be somewhat confusing to new users (Expensive or Expedient to whom?).  Eg: A 0.1% price above the CEX is red flagged as "Expensive", while brokers in traditional markets would say that stock prices within +/- 15% of a theoretical PE ratio are at a FAIR price.

Solution: Include a third category of "Fair".  The "Fair" category could be as wide as +/- 5% from the CEX price, but perhaps a +/- 2% spread is reasonable. Regnar#6164 agreed with 2% on discord 01/12/2022: "It wouldn't hide the actual discount/premium, but just add an additional category (and color?) to the presentation of the info." 

Personally I prefer the 3 terms Discount - Fair - Premium.  Discount is more customer-centric and readily implies better value. Premium immediately conveys a greater price, but also perhaps psychologically that the product is more valuable. (Eg. a customer is happy to pay a "Premium" for a more secure service.)

So as a suggestion (open to further community input): 
DISCOUNT (green) -- FAIR VALUE (blue) -- PREMIUM (red)

Thank you for your consideration.

**Comment by tonymorony** [comment]
Thank you for the issue opening! We'll definitely consider wording update for CEX price comparison widget in one of upcoming releases
