### ISSUE TITLE
[FEATURE REQUEST]: Provide a way to create a payment(withdrawal) on from clicking a link in a web browser

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/komodo-wallet#1568]
**Is your feature request related to a problem? Please describe.**
As far as I know, right now there is no way for a merchant to provide a payment url that opens AtomicDEX Desktop with the address and amount filled in for the user to complete the payment with a single click in a web browser.

**Describe the solution you'd like**
maybe create a new URI protocol like `atomicdex://litecoin/withdraw/address/LPUSYubqPVb46fGu88uGwR42u8jCBxqwqx/amount/0.1` or use one that is already used by other crypto wallet apps. I think electrum wallet and bitcoin-qt can both handle `bitcoin://.....`
https://superuser.com/a/587850
https://askubuntu.com/questions/1383898/bitcoin-uri-handling

**Comment by Seko1900** [comment]
Such a URI would be a feature and added value for AtomicDEX. 

Especially for webmasters who accept donations or payments via link or QR with KMD. The payment script could open the wallet directly via a URI.
https://github.com/SandroMachado/BitcoinPaymentURI

**Comment by tonymorony** [comment]
yeah, that's a good thing to have indeed

btw atomicdex mobile does support payment URIs for bitcoin and ethereum (like a bitcoin:...) and if you scan such QR code with atomicdex running OS should offer you to open it in it

**Comment by Seko1900** [comment]
> yeah, that's a good thing to have indeed
> 
> btw atomicdex mobile does support payment URIs for bitcoin and ethereum (like a bitcoin:...) and if you scan such QR code with atomicdex running OS should offer you to open it in it

Within AtomicDEX it works. If I read the QR via a browser, hold my mobile device to it, then AtomicDEX should open. In my case, the trust wallet opens. 

If I don't have the Trust and no other, should AtomicDEX open? Haven't tried it, honestly.

And this should work for all supported coins at best, but definitely for ecosystem coins.
