### ISSUE TITLE
[FEATURE REQUEST]: In the "import wallet" screen, allow a user to specify "privkey/wif"

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/komodo-wallet#1778]
**Is your feature request related to a problem? Please describe.**
Current "import wallet" screen allows importing a privkey, but it is ambiguous: https://forum.komodoplatform.com/uploads/default/original/1X/2f3699f235238af4b1aee0e9f0dfd1101a038ed2.png

A user has to select the "allow custom seed" option and then input the wif

**Describe the solution you'd like**
Instead of this, provide a toggle that allows switching between "seed words" and "wifs"
when the toggle is set to "wif", the UI must validate the input wif and reject it if it isn't valid

**Comment by smk762** [comment]
Will need:
- [ ] Private key format validation
- [ ] Toggle for selecting "seed phrase" or "private key" on import wallet page
- [ ] "allow custom seed" option hidden if "private key" selected
