### ISSUE TITLE
[BUG]: Order cancelled when balance changed

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#1787]
Related to https://github.com/KomodoPlatform/atomicDEX-API/issues/1254 & https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/591

One way to mitigate this could be with caching and comparing last valid electrum response to current incoming response and ignoring it if bad state (reporting confirmed funds as both confirmed and unconfirmed) is detected.

**Comment by cipig** [comment]
related https://github.com/KomodoPlatform/electrumx-1/pull/4
i wonder if this still happens
