### ISSUE TITLE
[FEATURE REQUEST]: notarytool usage instead of altool for OSX notarisations

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#1890]
Discovered while debugged nota process:

`Warning: altool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)`

**Comment by smk762** [comment]
Example of notary tool use - https://github.com/tauri-apps/tauri/issues/4300#issuecomment-1466915403

Apple docs: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

Handy migration guide: https://blog.dgunia.de/2022/09/01/switching-from-altool-to-notarytool/

When is fall? https://www.timeanddate.com/calendar/autumnal-equinox.html
I tried to find an actual date. Being a "king in the south", fall (known locally as autumn) has already happened. I assume that as Apple is part of the northern wasteland, it actually means September.
