### ISSUE TITLE
[FR]: pro-view orders / swap history list improvements

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#1969]
**Is your feature request related to a problem? Please describe.**
1a. Currently when looking at the orders and order history tabs, clicking on a line opens the order details. If it is an unmatched order, there is also a cancel button on the right (though it is only seen when under the mouse cursor). 

1b. The "cancel all" button is also hidden in the expanded filter form.

2. If I want to select the pair from an order line, I have to click too many times opening the two combo boxes and searching scrling to each coin. There must be a better way :thinking: 

**Describe your solution**
1a. display the cancel `x` on lines where order is cancellable.

1b. Move the "cancel all" button to the right of the button which opens the filter form, and display it when there are cancellable orders. 

2. Add an additional button on the order line which changes the selected orderbook pair to the pair on the selected line.

**Describe alternatives you've considered**
We could remove need  "cancel all", "cancel single order" & "go to pair orderbook" buttons, and use a right-click context menu instead. This would be a cleaner design, and leave more pixel area for other data.

**Additional context**
In some cases, a pair selected from the orders /swaps history line to update the orderbook will include a coin which is not enabled. In this case, a modal should appear to ask if user wants to enable that coin.

**Comment by SaltyCrocodile** [comment]
Yes, please!!  This -> 2. Add an additional button on the order line which changes the selected orderbook pair to the pair on the selected line.
