### ISSUE TITLE
[PROPOSAL]: Remove assets number limit configuration

### ISSUE THREAD

**Issue by ghost** [KomodoPlatform/komodo-wallet#2004]
This feature has been implemented following https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/884

This feature seems useless to me for few reasons:
- The user has to choose how many assets he wants to have if it's more than 50 (default value), why should we ask him to explicitly set a limit ? This is just one more step for the user to put his wallet ready to use.
- It's error-prone for the enabling logic. 
- It takes computation time for almost nothing in return.
- As an alternative we could show a warning message to the user if he's attempting to enable a huge number of coins
- It does not currently work well 
<img width="287" alt="Capture d’écran 2022-10-12 à 9 00 35 PM" src="https://user-images.githubusercontent.com/14373103/195426274-87a47ceb-d1e9-4548-99c7-ad7c7a35ad05.png">

**Comment by tonymorony** [comment]
the reason why #884 was proposed/implemented is that on some amount of assets added app starts hang/crash and user experience degradates without easy way for the user to get clues why

and it is quite easy for the user to use "select all" selector and activate all assets

if app will work stable with all available assets we can remove this limitation for sure

actually I do have a solution:

we can make all assets available in dashboard and "activate" it in background when user want to interact with this asset (e.g.  click in dashboard or select on DEX selector)
there are few moments which needs to be thought from UI/UX perspective, it's in a plan to add it into atomicdex web in next iteration, then we can just use the same approach in atomicdex desktop
