### ISSUE TITLE
[CI]: CI does not fail on build step even if compilation failed

### ISSUE THREAD

**Issue by ghost** [KomodoPlatform/komodo-wallet#2012]

**Comment by smk762** [comment]
I've noticed that local builds are also launching sometimes when there is build errors. Not sure if this is what is happening with CI also - will keep an eye out to link example CI logs here. 
workflow does have "continue-on-error" but only for test steps like https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/.github/workflows/atomicdex-desktop-ci.yml#L350 to ensure binary uploads are available (completed a step before tests)
