### ISSUE TITLE
[FR]: Export/Import address book 

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#2025]
It would be convenient if address book entries from one wallet could be exported, and imported into a different wallet (while still retaining existing address book entries).
In the event where an existing entry has the same name as one being imported but with a different address, the imported version should be named "original_name_imported", or "original_name_imported_x" where "x" is an incrementing number if `original_name_imported` already exists.

**Comment by SylEze** [comment]
Good feature !
