### ISSUE TITLE
[FR]: Allow source coins data update on demand

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#2035]
ref: https://github.com/KomodoPlatform/coins/issues/527#issuecomment-1297059615

**Is your feature request related to a problem? Please describe.**
Currently, when a new coin is listed it will not be available in AtomicDEX until the next release.

**Describe your solution**
The new unified coins config sourced from coins repo opens up the possibility for users to get "live" updates to their coins files when new coins are listed inbetween releases. This could best be achieved by adding a notification for the user and an "update coins" button in settings so they can update on demand.

**Describe alternatives you've considered**
It was suggested to do this on every app restart. This is possible, but will need to add a check to avoid downloading fresh when no changes have yet been made.

**Additional context**
To avoid potential errors, coins repo source should be pinned, otherwise it could result in app failing to load due to json parsing fail or structural changes to coins data as new methods are added to API. A simple API returning the current best commit hash or tag as coins repo reference will allow the app to have awareness of whether or not coins file is latest official version.

**Comment by SylEze** [comment]
Linked to #2015

**Comment by SirSevenG** [comment]
> It was suggested to do this on every app restart. This is possible, but will need to add a check to avoid downloading fresh when no changes have yet been made.

Coins repo commit (master) should suffice as validation i recon.

Also I think it would be better to keep updates manually. We can norify user that new config is available, but update itself is better done on "Reset configuration" press.

**Comment by estar-app** [comment]
Great idea, but that still depends on komodo platform. Creators will have to wait until komodo platform updates their coins list.

I think the komodo platform should also give creators the feature to update coins for their community users pending komodo platform's coins repo update as that might take either days or weeks of waiting after a PR was made by a craetor to komodo coins repo, since komodo is really focused now on enhancing aDEX.

Json parsing errors could be catered to by creators for their coins to activate.

**Comment by smk762** [comment]
> Great idea, but that still depends on komodo platform. Creators will have to wait until komodo platform updates their coins list.
> 
> I think the komodo platform should also give creators the feature to update coins for their community users pending komodo platform's coins repo update as that might take either days or weeks of waiting after a PR was made by a craetor to komodo coins repo, since komodo is really focused now on enhancing aDEX.
> 
> Json parsing errors could be catered to by creators for their coins to activate.

This is also planned - https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2103

Generally coins repo PRs are merged within 3-5 days tops if there is nothing missing and everything works.
