### ISSUE TITLE
[BUG]: SLP explorer rate limiting

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#2050]
After leaving app running idle in background for a while, when I went to visit https://simpleledger.info/ to check a coins contract for listing, I saw a "rate limit exceeded" error. We might need to setup our own node? 

![image](https://user-images.githubusercontent.com/35845239/200135843-a0204261-6a25-4d24-9741-0db2bc7bdcc2.png)

Pricing info: https://fullstack.cash/pricing/

We might be able to use this https://github.com/Permissionless-Software-Foundation/psf-slp-indexer or https://github.com/salemkode/slp-explorer-backend & https://github.com/salemkode/slp-explorer

**Comment by smk762** [comment]
cc: @tonymorony ^

**Comment by cipig** [comment]
what about https://simpleledger.at ?
