### ISSUE TITLE
[BUG]: Hover effects do not work on all platforms

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/komodo-wallet#2084]
**Describe the bug**
Hover effects that doesn't work for me on Win11:

1. Expand/Shrink left menu
- Login to wallet
- Mouseover Portfolio/Wallet/Dex/etc menue
- Menu does not expand
- Move mouse away
- Menu still does not react

2. Highlight asset line in Portfolio:
- Login to wallet
- Mouseover on asset in portfolio
- Line is not highlighted

3. Dex Simple/Pro buttons hints ⚠️ does not show info on hover
- Go to Dex Simple
- Mouseover SWAP NOW greyed button, hint part
- Nothing is shown

Hover effect that doesn't work on OSX and Win 11:

Fiat price source tooltip is not shown on mouseover
- Login to wallet
- On Portfolio mousover on Source column, any binance/coinpaprika/etc icon
- No tooltip is shown

Note: Didn't recheck on Linux, will entrust this one to @smk762 :)

**Comment by smk762** [comment]
I tested this on windows 10. First login was an old wallet, and no issue with hover effects. Next I tried a newer wallet and the sidebar did not expand. I did an assets reset and logged in to the second wallet again, and sidebar was expanding again.
Can you please try after an assets reset, and also with a newly created wallet?

**Comment by SirSevenG** [comment]
New wallet + assets reset helped, yeah.

**Comment by SirSevenG** [comment]
Got it once, can't easily reproduce for now.
Changing wallet and assets reset, as mentioned above, helped.
Will write here if able to reproduce.

**Comment by smk762** [comment]
Can confirm I also did not encounter this on mac (tested 3 different existing wallets without assets reset)

**Comment by SylEze** [comment]
Might be related to https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1985#issuecomment-1278109484
