### ISSUE TITLE
Balance scan on login or seed restore

### ISSUE THREAD

**Issue by dth88** [KomodoPlatform/komodo-wallet#210]
At the moment there is a UX problem - you might forget what coins you have balances on since seed restore activates only default coins. It might be great to do automagical detection on seed restore and also settings option to scan on login(probably enabled by default).

enabling all coins (in batches lets say, to not overload the app)
if balance > 0 OR tx_history_exists: activate coin
else: do nothing

[ https://github.com/ca333/komodoDEX/issues/785 ]
[ https://github.com/KomodoPlatform/atomicDEX/issues/138 ]

**Comment by Milerius** [comment]
@dathbezumniy In the answer from `enable_coin` and `electrum` there is no `balance_with_locked_funds` answer, it's can be a problem to determine the real value available for this balance at this moment

**Comment by smk762** [comment]
This might be best done as a button in settings to initiate an enable / disable if zero loop for all coins.
