### ISSUE TITLE
[FR]: Replace custom coin modals with coin listing form

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#2103]
**Is your feature request related to a problem? Please describe.**
The current method of adding custom coins is sub-optimal, as users can make errors with input, and it is limited to only 3 protocols with adding more or maintaining the existing process takes some time. Additionally, once a user adds their custom coin, it is unlikely they will have much luck on the dex unless other users have also taken the time to add the same coin.

**Describe your solution**
To allow for better curation / review of inputs, and to make the coin available to all users, it would be more efficient to covert this custom coin config generation to a coin listing request form, which on submission would add an issue to the coins repo with consistent formatting standards (to allow duplicate requests to become comments in the original) and as much info as the user can provide, with KMD team able to review and fill in any blanks. The form would need to be limited to the supported EVM networks and KMD SmartChains with standard input fields for each as required to construct the json and upload the icon. A link to the coins repo for more info (in readme) and requests for other coins could point users in the right direction for manually doing other listing requests.

**Downside**
Compared to the current way of adding custom coins, instead of them being instantly available for the user, there would be some delay for review / merge / update until it is available for all users. This delay would be reduced if/when https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2015 is implemented.

**Additional context**
We have numerous issues related to the custom coins:
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1508
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1879
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1286
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1354
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1424
- https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1425

We will also need to handle requests where ticker already exists in coins file, or a request has already been made but is still under review.

**Comment by gcharang** [comment]
> Compared to the current way of adding custom coins, instead of them being instantly available for the user, there would be some delay for review / merge / update until it is available for all users. This delay would be reduced if/when https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2015 is implemented.

to mitigate the downside, we can hide the current instant addition mechanism in settings to be enabled by advanced users and make the "coin addition request form" easily findable

**Comment by estar-app** [comment]
Ok! Great indeed.
