### ISSUE TITLE
[FR]: Make solid auto-updater

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#2108]
Thats what users need a lot, right now it's quite tricky to update the app

e.g.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/24797699/203834973-c32b69b1-1a59-41c3-abc8-33271525dc43.png">

**Comment by smk762** [comment]
This one should take care of "all assets taken over" once ready - https://github.com/KomodoPlatform/atomicDEX-Desktop/pull/1632 
I"ll revive and complete it.
For the installer issue, I'll check the IFW docs - there's been a few updates lately. Alternatively we can return to using Inno which had a working uninstall option in the installer wizard.
Currently a "Atomicdex maintainence tool" is included, but user has to find this in the install folder to run it which is not ideal.

**Comment by tonymorony** [comment]
> 

there needs to be "Update" button if new version is live and after user is clicking it update process should be handled automagically (optimally there might be an "Auto-update" optional checkmark so user will always be up to date)

**Comment by smk762** [comment]
You mean in app, not installer wizard? Like this, but for the whole app and not just coins? https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2035

**Comment by tonymorony** [comment]
> You mean in app, not installer wizard? Like this, but for the whole app and not just coins? #2035

yeah, exactly - whole app when new version is live
