### ISSUE TITLE
[FR]: show total available liquidity 

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/komodo-wallet#2121]
show the total avail. liquidity in orderbook view (on both sides) - missing entirely in pro view. In simple trading its shown but not sorted - add sorting icon, etc so we get a clean liquidity view.

**Comment by smk762** [comment]
As part of https://github.com/KomodoPlatform/komodo-wallet-desktop/pull/2383 the last 24hr trade value sourced from https://defi-stats.komodo.earth/ is now visible in app. Additional stats from same api will be trivial to include codewise, just need some design concepts for which stat and where to put it.
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/aa997a68-7c12-4347-9484-df624ea5ad01)
