### ISSUE TITLE
[BUG]: Orderbook scrolling losing focus

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#2145]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2116#issuecomment-1334569501

**Comment by cipig** [comment]
after switch of pairs or switch from Portfolio/Wallet to DEX, asks (red) should be scrolled to bottom, while bids (green) should be scrolled to top

**Comment by himu007** [comment]
as i can see the other issue is marked closed. thanks @cipig for pointing out this one. i've taken 2 screenshot to make it better understanable. the first picture shows the issue and 2nd one is how it should be. both screenshot taken from same orderbook at the same time.

![1](https://user-images.githubusercontent.com/8881040/212375436-21dd694d-7d00-4ac0-a87e-ba09e30609ef.png)
![2](https://user-images.githubusercontent.com/8881040/212375530-6d0026c6-bc48-4fe4-b979-2a3b854d351f.png)

this issue occurs when user clicks on DEX tab and any orderbook is displayed.

it also occurs different times when user has placed an order for swap.

**Comment by smk762** [comment]
> (https://user-images.githubusercontent.com/8881040/212375530-6d0026c6-bc48-4fe4-b979-2a3b854d351f.png) This is how it should be without user scrolling to the bottom of sell side of orderbook (red ones). this issue occurs when user clicks on DEX tab and any orderbook is displayed.

Ordering has been solved :heavy_check_mark: 

Inconsistent scrolling appears to still be present for the top half of the orderbook :no_good:
