### ISSUE TITLE
[CI] libwally build fails on MacOS

### ISSUE THREAD

**Issue by DeckerSU** [KomodoPlatform/komodo-wallet#2162]
During deploying jenkins builder for `atomicDEX-Desktop` faced with the `libwally` build fail. This issue describing error itself and available solutions.

`system_profiler SPSoftwareDataType` output:
```
Software:

    System Software Overview:

      System Version: macOS 12.6.1 (21G217)
      Kernel Version: Darwin 21.6.0
      Boot Volume: macOS
      Boot Mode: Normal
      Computer Name: osxbuilder
      User Name: builder (builder)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:49
```
`uname -a`:
```
Darwin osxbuilder.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64
```
Using the [following steps](https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/ci_tools_atomic_dex/ci_scripts/osx_script.sh#L37-L41) from official build guide to build `libwally`:
```
git clone https://github.com/KomodoPlatform/libwally-core.git
cd libwally-core
./tools/autogen.sh
./configure --disable-shared
sudo make -j3 install
```
We will get the following error on `make` stage:
```
Making all in src
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in secp256k1
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc -g -O2 -Wall -Wextra -Wno-unused-function  gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
./libtool: line 151: -o: command not found
  CCLD     libsecp256k1.la
./libtool: line 151: -o: command not found
error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
make[3]: *** [libsecp256k1.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```
Almost similar as error described in this issue: https://github.com/ElementsProject/lightning/issues/5118

Possible solutions:

1. Update https://github.com/KomodoPlatform/libwally-core repo to the latest https://github.com/ElementsProject/libwally-core .
2. Cherry-pick following commits https://github.com/ElementsProject/libwally-core/commit/a874a7782da73a91dc53dc8ef603a512d0932bc2 , https://github.com/ElementsProject/libwally-core/commit/2ac87a37fb318fa0139ae1b645b79eb34fe45125 from https://github.com/ElementsProject/libwally-core to our repo, or use the attached patch - [build-osx-patch.zip](https://github.com/KomodoPlatform/atomicDEX-Desktop/files/10169067/build-osx-patch.zip) during OSX build.

**Comment by smk762** [comment]
We faced the same problem in desktop CI a while ago, which led to this workaround - https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/ci_tools_atomic_dex/ci_scripts/osx_script.sh#L8-L10

We've got some CI upddates on the horizon for deprecating deps, will tag this to be included.
