### ISSUE TITLE
[FR]: Implement `UtxoPerKbyte` for custom fees

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#2186]
Requested via Discord - 
```
it's good to see that UtxoPerKbyte is any easily added implementation, a big upgrade, in my opinion.. allowing us to choose what fees we want to pay, depending on our price and time requirements..
as this value is always changing from block to block, i didn't feel equipped enough to know what fraction of btc to allocate... as you say, wouldn't want the tx to get stuck in the mempool for weeks... 
i feel i'd be more open to move funds in and out more freely, if that option was there. 
a nice addition i feel. 
```

**Comment by cipig** [comment]
those extimates are per kb... the fee you need to pay depends on the size of the tx, which you can't know beforehand since it depends on how many utxos are used as input for your tx, which you can't know before the tx is sent

**Comment by smk762** [comment]
A solution for this should include:
- toggle to switch from `fixed fee` to `fee per byte`
- where available, suggested prices (ideally via urls contained in coins repo)

**Comment by cipig** [comment]
> toggle to switch from `fixed fee` to `fee per byte`

idk if we actually need the `fixed fee`... i personally would say no... so i would just replace `fixed fee` with `fee per byte`

**Comment by cipig** [comment]
would be nice to have this, so people can send their DOGE with custom fees and get rid of them :-)
atm txes can get stuck because DOGE chain is spammed since couple months
