### ISSUE TITLE
[FR]: Add "AtomicDEX Tour" at the first start of the app

### ISSUE THREAD

**Issue by himu007** [KomodoPlatform/komodo-wallet#2199]
**Is your feature request related to a problem? Please describe.**
Many users don't know about `Pro View`. They just keep using simple view. Also they might not be aware of many good features of atomicDEX.

**Describe your solution**
It would be good to have `AtomicDEX Tour` which shows important information where user press `Next`...`Next`, `Finish` with a `Don't show this again` checkbox. Important things and features can be included in a card view including telling users about simple and pro view.

**Additional context**
Many apps and websites uses content like this to make users aware of new updates or how to use existing ones. i.e.: Binance does this for all new users on Spot or Futures trading (or when existing user logs in from a new/clean browser).

**Comment by tonymorony** [comment]
cf: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/450

**Comment by smk762** [comment]
Perhaps this might be best served as a series of videos, which can be linked to in the FAQ section or via a `?` icon for specific pages.
