### ISSUE TITLE
[BUG]: not enough balance error when starting swaps

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet#2210]
Sometimes i get the following error when i want to start swaps:
![image](https://user-images.githubusercontent.com/32116761/221304454-b6ab137a-42dd-41de-bec2-e5cf15761cb6.png)

I can't reliably reproduce it though... sometimes, after the error shows up, switching pair and then switching back to the initial pair "fixes" the problem.
atm i can't get around it, no matter what i do... even entering a different volume shows the same error, which makes no sense, since the resulting amount of JJPY-PLG20 should be totally different... see this second screenshot
![image](https://user-images.githubusercontent.com/32116761/221305293-3a54572a-642e-4837-8c1e-a03681f65bf4.png)
trying to buy 444 RTM (instead of 3927 shows the exact same error

the error shows up after clicking on "start swap"

**Comment by cipig** [comment]
i get this on KMD too

i click on an order in the orderbook to buy a coin (smart chain) with KMD and log shows
```
[20:14:41] [info] [qt.trading.page.cpp:1207] [3852795]: [determine_fees] trade_preimage answer received: [{"error":"rpc:211] dispatcher_legacy:141] dispatcher_legacy:158] taker_swap:2366] check_balance:75] Not enough KMD for swap: available 10617.45189773, required at least 10617.45189790213127413127413127413127413127413127413127413127413127413127413127413127413127413127413, locked by swaps Some(BigDecimal(\"0\"))"}]
```

if i then click on "Start Swap" in GUI, i get the same error in GUI and swap does not start, but log shows
```
[20:17:53] [debug] [main.prerequisites.hpp:87] [3852794]: Getting fees info... 1/50
[20:17:53] [info] [qt.trading.page.cpp:1207] [3852807]: [determine_fees] trade_preimage answer received: [{"result":{"base_coin_fee":{"coin":"DEX","amount":"0.00001","amount_fraction":{"numer":"1","denom":"100000"},"amount_rat":[[1,[1]],[1,[100000]]],"paid_from_trading_vol":true},"rel_coin_fee":{"coin":"KMD","amount":"0.00001","amount_fraction":{"numer":"1","denom":"100000"},"amount_rat":[[1,[1]],[1,[100000]]],"paid_from_trading_vol":false},"taker_fee":{"coin":"KMD","amount":"0.2629343629343629343629343629343629343629343629343629343629343629343629343629343629343629343629343629","amount_fraction":{"numer":"681","denom":"2590"},"amount_rat":[[1,[681]],[1,[2590]]],"paid_from_trading_vol":false},"fee_to_send_taker_fee":{"coin":"KMD","amount":"0.00001","amount_fraction":{"numer":"1","denom":"100000"},"amount_rat":[[1,[1]],[1,[100000]]],"paid_from_trading_vol":false},"total_fees":[{"coin":"DEX","amount":"0.00001","amount_fraction":{"numer":"1","denom":"100000"},"amount_rat":[[1,[1]],[1,[100000]]],"required_balance":"0","required_balance_fraction":{"numer":"0","denom":"1"},"required_balance_rat":[[0,[]],[1,[1]]]},{"coin":"KMD","amount":"0.2629543629343629343629343629343629343629343629343629343629343629343629343629343629343629343629343629","amount_fraction":{"numer":"3405259","denom":"12950000"},"amount_rat":[[1,[3405259]],[1,[12950000]]],"required_balance":"0.2629543629343629343629343629343629343629343629343629343629343629343629343629343629343629343629343629","required_balance_fraction":{"numer":"3405259","denom":"12950000"},"required_balance_rat":[[1,[3405259]],[1,[12950000]]]}]}}]
```
(i changed the amount to 1 before clicking on start swap, the max amount would have eaten all my balance)

so swap would work fine, but GUI does not let me start it because of the previous `determine_fees` error with the max amount

**Comment by smk762** [comment]
> why is trade_preimage even called when i click on an order in orderbook? is that needed? can we disable it? i see no infos that are shown before clicking on "start swap" and then a new trade_preimage is called anyway

@cipig some of the `trade_preimage` response is used to determine other values like max tradable volume after fees. As it is a slow method to respond, I suspect its race conditions that may cause a problem. There may be some newer API methods like `max_maker_vol`. 

Related discussion at https://github.com/KomodoPlatform/AtomicDEX-mobile-private/pull/1726

During 0.5.8 RC testing we will test this more intensively to determine if issue still present and how it can be replicated.

**Comment by cipig** [comment]
![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32116761/5db99ee9-7429-4754-b32c-a389c667a479)
trying to sell 345 IRIS out of 360 for LTC and getting this error
same error when i try to sell 50% (180 IRIS)

**Comment by cipig** [comment]
![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32116761/7a1fc919-4175-483c-99dd-ed10b12b844f)
it happens when you are about to buy a coin that needs spending your entire balance of the other coin (or close to it)
error shown in Desktop log: `[15:47:55] [info] [qt.trading.page.cpp:1207] [1054554]: [determine_fees] trade_preimage answer received: [{"error":"rpc:211] dispatcher_legacy:141] dispatcher_legacy:158] taker_swap:2398] check_balance:75] Not enough BCH for swap: available 0.01670641, required at least 0.016706817338158, locked by swaps Some(BigDecimal(\"0\"))"}]`

it does not always happen, i assume a rounding error and that's also what the error message indicates
i assume it happens in 50% of the cases based on price of order

**Comment by kaks25** [comment]
I still have this issue running on v0.6.1
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/65034388/d1ba90d5-112e-45b4-99d5-1e7829754341)

**Comment by cipig** [comment]
the problem seems to come from calling `eth_estimateGas` (likely called by `trade_preimage`) with values that are higher then your balance and which then lead to errors from RPCs `transfer amount exceeds balance`

example from PLG20:
```
[12:27:05] [debug] [qt.trading.page.cpp:1707] [951583]: reset_fees
30 12:27:06, mm2_main::rpc::dispatcher:121] ERROR RPC error response: taker_swap:2500] eth:5701] Transport error: request MethodCall(MethodCall { jsonrpc: Some(V2), method: "eth_estimateGas", params: Array([Object({"from": String("0x15c577f4b9fbe66735a9bff9b0b5d3ea2854bfaa"), "to": String("0x236aa50979d5f3de3bd1eeb40e81137f22ab794b"), "gasPrice": String("0x7c9f04109"), "value": String("0x0"), "data": String("0xa9059cbb000000000000000000000000d8997941dd1346e9231118d5685d866294f59e5b000000000000000000000000000000000000000000000000000002aceffa3967")})]), id: Num(6) }) failed: Invalid response: Server: 'https://block-proxy.komodo.earth/rpc/matic', error: RPC error: Error { code: ServerError(3), message: "execution reverted: ERC20: transfer amount exceeds balance", data: Some(String("0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000")) }
```

example from BEP20 with SOL-BEP20:
```
[12:33:49] [warning] [qt.trading.page.cpp:1058] [951583]: last_trading_error is BalanceIsLessThanTheMinimalTradingAmount
30 12:33:50, mm2_main::rpc::dispatcher:121] ERROR RPC error response: taker_swap:2500] eth:5701] Transport error: request MethodCall(MethodCall { jsonrpc: Some(V2), method: "eth_estimateGas", params: Array([Object({"from": String("0x15c577f4b9fbe66735a9bff9b0b5d3ea2854bfaa"), "to": String("0x570a5d26f7765ecb712c0924e4de545b89fd43df"), "gasPrice": String("0x77359400"), "value": String("0x0"), "data": String("0xa9059cbb000000000000000000000000d8997941dd1346e9231118d5685d866294f59e5b0000000000000000000000000000000000000000000000000004717cbf467411")})]), id: Num(1) }) failed: Invalid response: Server: 'https://bsc1.cipig.net:18655/', error: RPC error: Error { code: ServerError(3), message: "execution reverted: BEP20: transfer amount exceeds balance", data: Some(String("0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002642455032303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000")) }
```

my balance of SOL-BEP20:
![image](https://github.com/user-attachments/assets/568c1a56-58bf-4ebc-a206-28b0f42f9149)

i wonder why we need to pass a volume to `eth_estimateGas` at all, since the volume has nothing to do with txfees/gas... i pay the same txfee if i send 1000 TBTC-PLG20 or 0.00001 TBTC-PLG20
looks like we could omit `value` from `eth_estimateGas` calls: https://ethereum.stackexchange.com/questions/156455/eth-estimategas-throws-execution-reverted-error
looks like this issue is actually from mm2 and trade_preimage

**Comment by dimxy** [comment]
> it happens when you are about to buy a coin that needs spending your entire balance of the other coin (or close to it)
error shown in Desktop log: ... Not enough BCH for swap: available 0.01670641, required at least 0.016706817338158

I used the balances from screenshots above, for failed swaps IRIS/LTC and LBC/BCH, in our docker swap tests. Tests worked correctly and also final balances after swap became 0.
I assume when a user clicks to spend max volume the "max_taker_vol" rpc is called to get the max amount and later when the user starts swap "trade_preimage" is called for the max amount. (Those failed swaps actually threw errors in the "trade_preimage" rpc.)

My guess: the transaction fee increased between the max_taker_vol and trade_preimage calls (max_taker_vol trade_preimage rpc both get txfee) @cipig @shamardy 

(BTW for the IRIS/LTC swap it is even more unclear: the error showed that the max value around 360 was used but in the swap edit box the value was 345. Looks like a GUI issue)

**Comment by cipig** [comment]
> My guess: the transaction fee increased between the max_taker_vol and trade_preimage calls (max_taker_vol trade_preimage rpc both get txfee) @cipig @shamardy

LBC and BCH have a fixed fee https://github.com/KomodoPlatform/coins/blob/master/coins#L1580, like most of the UTXO coins. So at least for those it's not the fee.
I also guess that the error will not come if you use a certain amount to swap, but your balance is higher then that.

**Comment by dimxy** [comment]
BTW our doc for the [trade_preimage_rpc](https://komodoplatform.com/en/docs/komodo-defi-framework/api/v20/trade_preimage/) advises not to use the max volume directly for set_price rpc. I think this makes sense.
Maybe the trade_preimage_rpc should return the max volume with some tolerance (lower bound)
