### ISSUE TITLE
[FR]: make left-alignment for `receive/sent` status column on coin details page

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/komodo-wallet#2249]
It looks a little bit weird and chaotic now. Other columns are aligned by one side.

<img width="1726" alt="Screenshot 2023-04-12 at 12 14 26" src="https://user-images.githubusercontent.com/77272165/231441515-52d17b18-c490-4727-8540-2461fded82ff.png">

**Comment by endrilickollari** [comment]
Same issue in Windows 10: 

![image](https://user-images.githubusercontent.com/32954585/231447765-b4b9ab69-5992-44ef-a8b6-d67962a8206d.png)
