### ISSUE TITLE
Avoid Windows protection notification on installing and opening the AtomicDEX-Desktop

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/komodo-wallet#2261]
hey @cipig  @smk762 do you know is it possible to avoid this notification on Windows?

The publisher is unknown and the user sees this notification when installing and every time opens the app

![Screenshot 2023-04-12 135358](https://user-images.githubusercontent.com/77272165/231552628-26080b5c-0136-488b-8e24-ad39c9505031.png)

Branch `0.5.7.2` commit https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/a9118c98fb7d833754a092bf0bc546be99614e99
tested on Windows 11

**Comment by smk762** [comment]
Looks like we need a code signing certificate, then we can use an action like https://github.com/Dana-Prajea/code-sign-action or run https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool as part of the build flow.
