### ISSUE TITLE
[BUG]: Crush report 

### ISSUE THREAD

**Issue by Canialon** [KomodoPlatform/komodo-wallet#2264]
@smk762  @endrilickollari @cipig  can you please try on you side?

**To reproduce:**
1. Go to Settings -> set max number of enable coins to 200
2. Go to the Wallet/Portfolio tab -> Enable assets -> select all assets -> enable
3. Right click on any asset -> disable all
4. Repeat steps 2 and 3 few times

**More details:**
- On my side I need to release steps 2 and 3 only once to trigger crush. 
- Also after opening app again I cannot login to any wallet -> see the endless loading and initializing MM2 (To fix have to run `pkill -9 mm2`)
- Maybe need to have few swaps in progress
- I was not able to reproduce this bug on Windows 11

**Logs**:
```
14 12:16:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
14 12:16:22, coins:rpc_clients:2375] ERROR "electrum1.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
14 12:16:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
14 12:16:22, coins:rpc_clients:2375] ERROR "electrum2.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
14 12:17:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
14 12:17:22, coins:rpc_clients:2375] ERROR "electrum2.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
14 12:17:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
14 12:17:22, coins:rpc_clients:2375] ERROR "electrum1.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
```
and 

```
[13:07:14] [error] [mm2.service.cpp:2472] [420766]: pplx task error: Failed to read HTTP status line from: fetch_single_balance, request: [
    {
        "coin": "BCH",
        "method": "my_balance",
        "userpass": ""
    }
]
[13:07:15] [error] [mm2.service.cpp:2472] [420209]: pplx task error: Failed to read HTTP status line from: fetch_single_balance, request: [
    {
        "coin": "AXE",
        "method": "my_balance",
        "userpass": ""
    }
```
Can send full log files

**Tested on:**
Branch: `0.5.7.2` 
Commit:  8d5ac29dc6f4f86425840ad8fe0cb35d6d9d9379 
CI build -> installer and dmg
OS : MacOS 13
Chip: Apple M1

**Comment by endrilickollari** [comment]
> @smk762 @endrilickollari @cipig can you please try on you side?
> 
> **To reproduce:**
> 
> 1. Go to Settings -> set max number of enable coins to 200
> 2. Go to the Wallet/Portfolio tab -> Enable assets -> select all assets -> enable
> 3. Right click on any asset -> disable all
> 4. Repeat steps 2 and 3 few times
> 
> **More details:**
> 
> * On my side I need to release steps 2 and 3 only once to trigger crush.
> * Also after opening app again I cannot login to any wallet -> see the endless loading and initializing MM2 (To fix have to run `pkill -9 mm2`)
> * Maybe need to have few swaps in progress
> * I was not able to reproduce this bug on Windows 11
> 
> **Logs**:
> 
> ```
> 14 12:16:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
> 14 12:16:22, coins:rpc_clients:2375] ERROR "electrum1.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
> 14 12:16:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
> 14 12:16:22, coins:rpc_clients:2375] ERROR "electrum2.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
> 14 12:17:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
> 14 12:17:22, coins:rpc_clients:2375] ERROR "electrum2.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
> 14 12:17:22, rustls:conn:1274] WARN Sending fatal alert BadCertificate
> 14 12:17:22, coins:rpc_clients:2375] ERROR "electrum1.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
> ```
> 
> and
> 
> ```
> [13:07:14] [error] [mm2.service.cpp:2472] [420766]: pplx task error: Failed to read HTTP status line from: fetch_single_balance, request: [
>     {
>         "coin": "BCH",
>         "method": "my_balance",
>         "userpass": ""
>     }
> ]
> [13:07:15] [error] [mm2.service.cpp:2472] [420209]: pplx task error: Failed to read HTTP status line from: fetch_single_balance, request: [
>     {
>         "coin": "AXE",
>         "method": "my_balance",
>         "userpass": ""
>     }
> ```
> 
> Can send full log files
> 
> **Tested on:** Branch: `0.5.7.2` Commit: [8d5ac29](https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/8d5ac29dc6f4f86425840ad8fe0cb35d6d9d9379) CI build -> installer and dmg OS : MacOS 13 Chip: Apple M1

In my Windows 10 looks everything okay

**Comment by endrilickollari** [comment]
> 

Did the steps 3 times, not an issue, could not reproduce it

**Comment by Canialon** [comment]
> Did the steps 3 times, not an issue, could not reproduce it

Thanks! Same here on Windows 11, it can be a Mac specific issue, need to try on another Mac device

**Comment by smk762** [comment]
no crash here yet on linux but I see the same error
```
14 12:40:40, rustls::conn:1274] WARN Sending fatal alert BadCertificate
14 12:40:40, coins::utxo::rpc_clients:2617] ERROR "electrum1.aryacoin.io:2053" error Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertExpired") }
```
