### ISSUE TITLE
[FR]: Can't shrink atomicDEX-Desktop application enough to see the entire width

### ISSUE THREAD

**Issue by 2011** [KomodoPlatform/komodo-wallet#2270]
**Is your feature request related to a problem? Please describe.**

I run a normal full HD monitor in portrait mode (1080x1920). When I start atomicDEX-Desktop (using the Linux AppImage) it won't fit on the screen, and I can not shrink it enough to fit on the screen.

I would prefer that the application allow more resizing (even if it comes with smaller text and images, or requires a rearrangement of the visible elements).

**What problem does your suggestion solve? E.g. It would be more convenient if [...]**

It would let me see the entire application at once without having to move it left and right to see the parts that don't fit.

**Describe your solution**

Would like the application to allow shrinking the size down to the resolution (width) of my monitor (even scrollbars in the workspace would beat having to always move the application window left and right all the time).

**Describe alternatives you've considered**

None (not going to change my monitor orientation just to use this application).

**Comment by smk762** [comment]
Which OS?
Is there any scaling in your display settings?
Can you please post a screenshot to indicate where it cuts off?
Does the issue persist when app is maximised?

**Comment by 2011** [comment]
> Which OS?

Compiled from source.

Built from source.

kernel: 6.1.28
glibc: 2.36
gcc: 12.2.1
binutils: 2.39
python: 3.11.3

Lumina (fluxbox) desktop

> Is there any scaling in your display settings?

No.

> Can you please post a screenshot to indicate where it cuts off?

Sure. I took these after making the app as narrow as possible:

![atomicDEX-0](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/550150/4ad1092a-e065-4361-ae9a-791b7562bae9)

![atomicDEX-1](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/550150/3d99fd11-29e0-447e-af73-33dedf88f9c4)

> Does the issue persist when app is maximised?

I guess (by eliminating the menu on the left) the application does show the entire width of the asset list. Note that the minimize, maximize, and close controls do not display (although they still function).

![atomicDEX-2](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/550150/0b3992d8-3b65-4277-b835-95a739010488)
