### ISSUE TITLE
[BUG]: Overflow goes to table header, need to be visible only in coins list

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/komodo-wallet#2308]
At simple trade view, after completing "from" at "to" coin some suggestions appear, but overflow goes to table header, need to be visible only in coins list.

So the overflow have to appear only in green rectangle: 

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/fe815aaf-ba29-42bd-bd3c-c010eebac408)

**Operating Environment(s):**
 - OS: Windows
 - OS version: 10
 - AtomicDEX Version: 0.5.8

**Comment by smk762** [comment]
Issue still present Aug 2024
