### ISSUE TITLE
[FR]: Enhance font size in some part of the application

### ISSUE THREAD

**Issue by endrilickollari** [KomodoPlatform/komodo-wallet#2315]
- At the responses at FAQ.

   
![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/a026eb87-e982-462c-ac85-12b3106180f7)

- At "Add coins" modal.

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/40c6b25c-553e-4088-b049-62aeaad6a39b)

- At transaction history.

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/7b4b4cfb-af62-45f7-a0a8-96505194d94d)

- At "Wallet" view, coins font to be bigger.

![image](https://github.com/KomodoPlatform/atomicDEX-Desktop/assets/32954585/006dd1df-8e15-46ed-b93f-219a9f217078)

will also check some good practices for font sizes.

**Comment by smk762** [comment]
On hold for now - this could be part of an appwide update to scale text etc based on window size or screen res
