### ISSUE TITLE
[BUG]: chart/pair selection has fixed width in Pro view

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet#2366]
currently, if i make the window wider on DEX Pro view, it looks like this, only orderbook is made wider
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/ef85f462-9439-4980-b1fd-703351c7cf9d)

it would be good to keep orderbook at fixed width and make the part with the charts and coin selection wider
that way the full name of the coin would be visible and the chart would have more room

(charts are not showing up here, idk why, it's since some time and idk what the problem is, but that is a different issue)

**Comment by smk762** [comment]
This is on purpose at the moment due to chart scaling issues. When a better solution for current charts is found, this can be more flexible

**Comment by cipig** [comment]
can we make pair selection 4 columns then, since current layout leads to this?
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/4a7d3edb-f5e1-4bd0-b298-715bf877a233)

**Comment by smk762** [comment]
I think the best approach here would be a network overlay like on web app for tokens so the ticker text can be redacted.

**Comment by smk762** [comment]
> can we make pair selection 4 rows then, since current layout leads to this? ![image](https://private-user-images.githubusercontent.com/32116761/292647900-4a7d3edb-f5e1-4bd0-b298-715bf877a233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTA2MjIsIm5iZiI6MTcxODI1MDMyMiwicGF0aCI6Ii8zMjExNjc2MS8yOTI2NDc5MDAtNGE3ZDNlZGItZjVlMS00YmQwLWIyOTgtNzE1YmY4NzdhMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzNDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTg4MjVlOTc0YjFkYzVhODg0M2JjNGI4YTNjZWNiODcyYTM2ZWZkNzlkMWZmYjNkM2IwYTE5NWY4MWI3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTFpdE-BVhAsSlyBLah9FQuFEbiFgz8C-XN5FeKoHUE)

v0.7.1 has the 4 line layout

![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/f46973c0-dc12-464f-be09-e06a7dff9510)
