### ISSUE TITLE
[BUG]: Update the Transaction Status from "Unconfirmed" to - Transactions in Mempool/Awaiting Confirmation. As status 'Unconfirmed' is misleading with the actual status.

### ISSUE THREAD

**Issue by ShantanuSharma9873** [KomodoPlatform/komodo-wallet#2430]
**Describe the bug**
The current status label "**Unconfirmed**" for ongoing transactions is misleading as it does not accurately reflect transactions in the mempool or awaiting confirmation. 

**To Reproduce**
1. Go to 'Komodo Platform' WebApp
2. Connect to an existing wallet/Create a new Wallet.
3. Move to the DEX tab and Swap between two coins.
4. Proceed to '**Start Swapping**' by adding the correct Taker & Maker order.
5. Move to the Wallet and open the Coin's transaction in between the ongoing Swap.
6. Notice that the '**Unconfirmed**' status is displayed even for the on going swap transaction.

**Expected behavior**
The status "**Unconfirmed**" should be replaced with '**Transaction in Mempool** OR '**Transaction Awaiting Confirmation**'.

**Operating Environment(s):**
 - OS: [ Windows]
 - Komodo Wallet Version: [0.7.2]
 - Build branch: [Prod] 

**Additional context**
 - https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/167987768/4b6fe0cd-b3e1-4565-b87c-d2e00354e18a

**Comment by smk762** [comment]
I was unable to get see a transaction in "unconfirmed" state while working on this. This might be due to the latest API changing how balance chances are detected. Will require further investigation, so I'll push this issue for the next version.
