### ISSUE TITLE
[FR]: How to find coins with balance?

### ISSUE THREAD

**Issue by sinancay1** [KomodoPlatform/komodo-wallet#2460]
Imagine; I enabled a coin and received some balance then I disabled that coin so it's not on portfolino anymore. 

And lets say I forgot the name or I forgot that I got balance on that coin.

"Add Crypto" screen has no means to find cryptos with balance, so how  do I find/know that crypto and access to balance?

1.Solution: Prevent disabling cryptos with balance

2. A better Solution "Add Crypto" screen may have checkbox to show cryptos with balance, so it gets easier to find cryptos with balance and enable that asset.

**Comment by smk762** [comment]
This could be achieved with an activation loop to scan for balances and disable any that are empty, but it is a little resource intensive, or scan takes a long time.
Alternatively, balance could be requested via electrum etc then activate any returning a non zero response.
