### ISSUE TITLE
[BUG]: "receive" amount of swap does not fit into field

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/komodo-wallet#2461]
if i click on the order selling ~2501 JASMY-BEP20, the receive amount does not fir into the field:
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/32116761/1ddb5bf4-81c6-4bd9-80c7-1b7a3dd5d98f)
maybe we can make the field using 2 lines

**Comment by smk762** [comment]
Due to horizontal space constraints, Can't really add a new line without something else falling off the page in some cases. 
Best I can do for now is to reduce the font size of the ticker. Do you think the protocol being included in that part is needed?

**Comment by cipig** [comment]
> Do you think the protocol being included in that part is needed?

No, i don't think it's needed... wasn't that already removed and then re added because of something?

**Comment by ShantanuSharma9873** [comment]
Here, the price and sending amount both fit within the field, but I noticed that there's no character limit enforced. Users can enter an unlimited number of digits, which allows the amount to increase indefinitely when more numbers are added.
![image](https://github.com/user-attachments/assets/5dbdfe69-809f-4c3c-b2d8-6fd61b9a01b3)

**Comment by cipig** [comment]
> I noticed that there's no character limit enforced. Users can enter an unlimited number of digits, which allows the amount to increase indefinitely when more numbers are added.

i don't think we can enforce a limit on volume and price, since there are coins/tokens worth almost nothing (eg look in BTTC-BEP20/KMD orderbook), so volume and price can be pretty big
