### ISSUE TITLE
[BUG]: Recent Swaps calendar does not update when the app is running when the month changes

### ISSUE THREAD

**Issue by jansako** [KomodoPlatform/komodo-wallet#548]
**Describe the bug**
AtomicDex 0.3, Win 10
The 'Recent swaps' list does not display swaps that happen some time after the calendar rolls over to the next month. A swap completed at 04.00am does display, a swap completed at 07.30am did not.
The filter on the calendar was also stuck, I was unable to roll over to next month or select today's date (31.10.2020), even if it was highlighted.
Restarting AtomicDex has fixed the issue.

**To Reproduce**
Have the application running during change from one month to the next.
Perform a swap, or several without closing Dex
At some point the 'recent swaps' will no longer display the swap just completed. Check the behavior of the calendar UI.

**Expected behavior**
The recent swaps show all my recent swaps in the default range (date X - today) instead of (date X - date y) 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/34211887/97777326-b0950800-1b2c-11eb-8016-dd71c6463dac.PNG)
There should be another swap on the list, this one:
dde660b5-5352-4f56-a020-4962c589fa7a    2020-10-31 07:29:40

**Desktop (please complete the following information):**
 - OS: Win10
 - version 0.3

**Comment by naezith** [comment]
I am working on light theme at the moment, I pushed the commit to that branch. Just a tiny change, increasing the higher date limit +30 days, to avoid similar issues. https://github.com/KomodoPlatform/atomicDEX-Desktop/commit/d6fa9e5fd9161f46f2dfe981270d127908405a06

**Comment by jansako** [comment]
Just to complete the report, this issue is also present on the 'orders' page. Ongoing orders are not displayed when the date rolls over.
