### ISSUE TITLE
[FEATURE REQUEST]: Display the maker's setting of number of confirmations for each order in the Orderbook 

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/komodo-wallet#622]
**Is your feature request related to a problem? Please describe.**

Currently, a taker doesn't know the number of confirmations a maker expects before accepting a transaction as final. For trades involving small amounts, it can cause incredible frustration to the taker if they didn't know that the trade was going to take a long time ( >> 30 minutes )    

**Describe the solution you'd like**
Display the approximate(may be minimum) amount of time the trade may take. Based on blocktimes of the coins involved and both the maker and taker's requirement for confirmations. This can allow a taker to choose one order over another based on this criterion. If only one such order is present, the taker may choose to not trade at all, based on their situation.

**Comment by naezith** [comment]
I think we don't have that information available at the API. https://developers.komodoplatform.com/basic-docs/atomicdex/atomicdex-api.html#orderbook

**Comment by smk762** [comment]
API now provides the info required for this

**Comment by smk762** [comment]
This should be displayed as both a tooltip when hovering over a line on the orderbook, and also within the swap confirmation screen.

**Comment by smk762** [comment]
This info is now available in the API response, not has not yet been added to the back end models.
