### ISSUE TITLE
[FEATURE REQUEST]: Address Book Features

### ISSUE THREAD

**Issue by theblackmallard** [KomodoPlatform/komodo-wallet#694]
I have a few feature ideas in regards to the AtomicDEX address book.

1) Addresses separated into user-owned and external addresses. For example, at the top of the address book should be a collapsed section called "My Wallets" that opens to show address book entries specifically owned by the user. This would create a clear distinction between internal and external addresses (addresses of friends, companies, peers or others)

2) Address book entries could also have the option to send all "types" of a coin or token to a particular address. For example, all ERC 20 tokens to a single ETH address, all Komodo coins to a single KMD address, QRC20 etc. This would simplify the process of adding a single address like "Verus Desktop" or "Paper Wallet" and putting a KMD address, which you can then send VRSC/SUPERNET/THC or others there. This currently requires a roundabout way to send non KMD coins to a KMD address because clicking "Send" on the address book opens KMD wallet, which you'd then have to copy and paste the address into the send for the coin you actually wanted to send.

3) Address book could also have some default address entries without the addresses at the start so that people have a good idea of what they can use them for. For example, AtomicDEX Mobile, Ledger Nano X, Discord TipBot, Verus Desktop, KMD Paper Wallet etc. then people can delete them or fill them with their own addresses.

4) Address book could be used for a simple implementation for donation addresses, originally in mind was for the Dogecoin team, but downloads could already include a team donation address/name in the address book.

5.a) Address book could have a reminder to send funds for donations/sending, for example donating 10 KMD to a Komodo donation address every month. The address book could have a "set reminder" option where it reminds you (assuming the wallet is opened) that you wanted to send funds. 

5.b) This could in the future also be a way to tie in some KMD usage, users could then allocate some of their 5.1% rewards to donations, and there could be an option to auto convert the KMD to the preferred donation coin via AtomicDEX. For example, using 10% of your monthly KMD rewards to auto convert to DOGE and donate to Dogecoin team.

**Comment by smk762** [comment]
- [ ] 1. Address entry categorisation _implemented via tags_
- [ ] 2. Address types option e.g. ETH, smart chain etc. _implemented_
- [ ] 3. Default address entries as example. _we could add a link to the https://dexstats.info/gas.php addresses here. Ideally a hyperlink to the site could be incorporated, and this option might be handy for other address entries_
- [ ] 4. Default example donation addresses. _should limit this to verifiable recipients like https://www.eff.org/pages/other-ways-give-and-donor-support#crypto_
- [ ] 5a. Periodic payments notification _clicking on this notification could prefill a send form for the user, but would mean adding extra forms to the addressbook to setup_
- [ ] 5b. Rewards allocation. _could trigger a send reminder notification after rewards received_
