### ISSUE TITLE
[FR]: Offline staking

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/komodo-wallet#719]
**Is your feature request related to a problem? Please describe.**

Offline staking will be possible with mm2 soon, we need to add new views in the UI to prepare such a feature.

**Describe the solution you'd like**

A dedicated staking page like on `atomicwallet`

**Additional context**

- QTUM / KMD will be supported at the beginning

**Comment by artemii235** [comment]
@smk762 It's implemented on the API side in the dev branch. I guess it can be done in GUIs before https://github.com/KomodoPlatform/atomicDEX-API/pull/1184 merge.
