### ISSUE TITLE
[FR]: Enable test coins via settings

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#745]
current test assets on desktop: tQTUM, test QRC20, tBTC, RICK/MORTY

cases for warning message appear:
- when user <buy> test coin for non-test coin
- when user <sell> test coin for non-test coin 

(when user trade test coin for test coin there should be no warning)

```
Text:
Warning, you willing to <sell>/<buy> test coins WITHOUT real value

```

example of implementation on mobile:
![image](https://user-images.githubusercontent.com/24797699/111447358-f18a6380-873f-11eb-9e8f-c47b74b1d4df.png)

**Comment by tonymorony** [comment]
on mobile, we decided to disable not RICK/MORTY test assets in settings since this feature is oriented on developers/testers. I think it's might be good to do it same way on the desktop:

![image](https://user-images.githubusercontent.com/24797699/120887732-d0d6f900-c61e-11eb-92df-96e2a4db3dc2.png)

**Comment by smk762** [comment]
Before implementing this, we need to standardise testcoin tagging 
ref: https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/1194
