### ISSUE TITLE
[FEATURE REQUEST]: Better self update system on Windows

### ISSUE THREAD

**Issue by ghost** [KomodoPlatform/komodo-wallet#865]
**Is your feature request related to a problem? Please describe.**
- We recently released our self update system in https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/714.
- Basically, it downloads latest release files and copies/pastes them inside AtomicDEX folder. 
- The self update system is contained inside the AtomicDEX application which leaded to new issues: on Windows, you cannot replace files which are already used by a process, which is not the case on Linux or MacOS (tell me if it's wrong or not accurate). However, renaming used files is possible ! 
- As you deduced, our workaround was to rename every AtomicDEX folder's file so there will be no conflicts when copying the update ones.

I'm sure this workaround will be someday error/crash prone. 

**Describe the solution you'd like**
Having an external tool (probably another executable) which is only dedicated to update AtomicDEX.

**Comment by smk762** [comment]
@SylEze since the recent updater checking, has this been implemented?
