### ISSUE TITLE
[FEATURE REQUEST]: Enhanced swap step txid links

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/komodo-wallet#878]
We have a bit of extra space in the "Swap details" modal on the right next to the swap steps - 
![image](https://user-images.githubusercontent.com/35845239/116878477-01a7c500-ac52-11eb-9201-496b6f0c9ca6.png)
Currently in the image above, I can click on the  "View on Explorer" button, and it will open a browser tab for the `maker payment spent txid` and/or `taker payment spent txid`. It would be nice to link to the other parts of the swap also.

**Describe the solution you'd like**
In the extra space to the right of `taker fee sent`, `maker payment received` and other steps involving a transaction, we could include the txid of each step within the modal, along with a explorer link button for each step.

**Additional context**
This extra info will "expose" the address on the other side of the trade, though on public chains this is already available with a little digging so does not significantly reduce privacy.

**Comment by tonymorony** [comment]
cf: https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/1073
