### ISSUE TITLE
[FEATURE REQUEST]: Additionally warn user if fees in his swap > 20(?)% of his swap amount

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#887]
more details TBD

**Comment by smk762** [comment]
One option here could be to include a line "Fees as percentage of trade value"  to the fee details area on order placement confirmation, with a red highlight if it is over a specific value.
E.g.
![image](https://user-images.githubusercontent.com/35845239/177270674-a67ca6cb-aa2a-45fd-a1ef-7a1044768107.png)

**Comment by smk762** [comment]
@tonymorony if you think the suggestion in my last comment is a viable solution please let me know. It should be relatively trivial to implement and could be included in 0.5.8

**Comment by smk762** [comment]
Closing - Warning exists in confirmation window
![image](https://github.com/KomodoPlatform/komodo-wallet-desktop/assets/35845239/d52695d8-d3e4-4daf-83ca-892f2c338f5c)
