### ISSUE TITLE
[BUG]: Privacy Filter on still shows the balance

### ISSUE THREAD

**Issue by CHMEX** [KomodoPlatform/komodo-wallet#939]
**Describe the bug**

**To Reproduce**
1. Go to '...' DEX View
2. Click on '....' Privacy Filter On Option

**Expected behavior**
I expect the Balance in my wallet to show ****** Meaning now shown
but it still shows the balance trades are shown as ******** so all good there
**Screenshots**
![image](https://user-images.githubusercontent.com/33424502/119320121-85fece00-bc7b-11eb-8bb9-67f5b7e0717c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Desktop v0.4.3-beta

**Comment by smk762** [comment]
To do this right we'd also have to disable trading while in privacy mode or else people might be trading blind.
