### ISSUE TITLE
[FEATURE REQUEST]: Implement orders history RPC call support

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#954]
API PR: https://github.com/KomodoPlatform/atomicDEX-API/pull/936
Documentation PR: https://github.com/KomodoPlatform/developer-docs/pull/256/files

Most probably we should consider the separation between trades (swaps) and orders history. Screenshot from Binance for ref:
![image](https://user-images.githubusercontent.com/24797699/120642562-4320cf80-c49f-11eb-8a6a-564d3a707a1e.png)

**Comment by Milerius** [comment]
I agree but in your case, Order History and Trade History is exactly the same, the only difference is that the Order History contains cancelled orders which is not interesting at all in the case of binance.

And Binance do it for a reason, they separate the swallowing of multiple orders with the initial wished trade.

If you want to sell 500 KMD, you can do it with hitting multiple orders, but it's still a single trade from the trade history view, we cannot do that for the moment in AtomicDEX (I mean in our case there is no difference between order and trade history no ? (Just the order that are cancelled but not really interesting)

**Comment by tonymorony** [comment]
@Milerius Think about the cases of automated LP / orders update / rebalancing - you likely want to check what bot did and if a strategy works correct over the time and what orders it placed/cancelled even if it's not matched

**Comment by cipig** [comment]
i hope this also works with 4000 orders updated every 3-4 minutes... if there are problems expected, it would be good to be able to disable the recording of order history

**Comment by smk762** [comment]
This should be able to be derived from the MM2.db. As it includes changes to the UI, it would be good to get some suggested options from our design team cc @tonymorony
