### ISSUE TITLE
[FEATURE REQUEST]: Prices < 0.00000001 handling

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#955]
I do propose to have fixed field size and display an amount such edge cases in scientific form (e.g. 2.2E-10 ETH) with full number displaying on mouseover (that's optional) - that's looks like the most straightforward solution

Other possible options coming to mind:
a) Teletext e.g. https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/1123
b) Printing prices in most little fractions of asset e.g. weis ( looks complicated since different assets got different fractions + what about prices less than satoshi for UTXO coins)

cf: https://github.com/KomodoPlatform/atomicDEX-API/issues/922

**Comment by Milerius** [comment]
> I do propose to have fixed field size and display an amount such edge cases in scientific form (e.g. 2.2E-10 ETH) with full number displaying on mouseover (that's optional) - that's looks like the most straightforward solution
> 
> Other possible options coming to mind:
> a) Teletext e.g. [KomodoPlatform/AtomicDEX-mobile#1123](https://github.com/KomodoPlatform/AtomicDEX-mobile/issues/1123)
> b) Printing prices in most little fractions of asset e.g. weis ( looks complicated since different assets got different fractions + what about prices less than satoshi for UTXO coins)
> 
> cf: [KomodoPlatform/atomicDEX-API#922](https://github.com/KomodoPlatform/atomicDEX-API/issues/922)

This is an important, one, the good things is that it's only concern the `price` field, we can also maybe do something with font size and the number of digits, however i think every coins need a settings decimals for his orderbook, and that depends with which coin you trade usually.

**Comment by damascene** [comment]
How would someone write the scientific format in the price filed, to setup a trade like in this case: https://github.com/KomodoPlatform/atomicDEX-API/issues/922#issuecomment-922184125

**Comment by samurai321** [comment]
I think another solution to this problem could be to only allow the trade of coins with low value in groups of 1000.

**Comment by smk762** [comment]
When the lightning hits, we'll need a solution for this.
