### ISSUE TITLE
[FEATURE REQUEST]: Custom portfolio currency selection

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#958]
At the moment it's possible to choose portfolio evaluation between fiat/btc/kmd/ltc 

probably some users want to count his portfolio value in lets say DOGE or ETH/BNB - I think it might be worth adding a "custom portfolio currency" setting (LTC by default with a possibility to change it to any crypto for which we got fiat price)

**Comment by ssakone** [comment]
ok i m going to focus on it.
