### ISSUE TITLE
[FEATURE REQUEST]: CI/CD speed up

### ISSUE THREAD

**Issue by tonymorony** [KomodoPlatform/komodo-wallet#969]
@smk762 could you please research on self-hosted runners connection?
Feel free to DM me for test machine providing

**Comment by smk762** [comment]
Will give it a shot. Did a little reading, seems there is still a security concern warning  with self-hosted runners on public repos - https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github
Will research how to mitigate this.

**Comment by cipig** [comment]
How about using self hosted runners based on AWS spot instances? Those can be provisioned in couple seconds with ready images. Those images contain the entire build environment, so no need to install/remove packages before every build, which speeds up the entire process. After compilation is done, destroy the instance, that way preserve the security mentioned in the docs and also only pay couple cents for 30 minutes runtime. If you want to further improve build time, simply replace the instance type in the call with one with better/more CPUs/cores. I don't know though how it works with Windows and MacOS environments, only know how it works with Linux.
